name: Testing configuration Variables

on:
  workflow_dispatch

env:
  cloud: google-cloud

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello to Vishal"
        run: echo "$Greeting $First_Name is using $cloud with project ${{ vars.PROJECT_ID }}!"
        env:
          First_Name: Bikram


# In this example what we using one workflow variable "cloud: google-cloud" 
# Here we are not defining project_ID within the workflow project ${{ vars.PROJECT_ID }} so I have to define my PROJECT_ID in GitHub repository settings
# When you use configuration variables use two curly braces. Context ${{ vars.PROJECT_ID }}
