name: Terraform GCP Deployment

on:
  push:
    paths:
      - '**.tf'
      - '.github/workflows/terraform.yaml'
    branches:
      - main

jobs:
  terraform:
    name: Terraform Init, Plan, Apply
    runs-on: self-hosted

    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Terraform CLI (with version)
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
          #cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}  # Optional: for Terraform Cloud, remove if using GCS backend only

      # Initialize Terraform (loads backend config)
      - name: Terraform Init
        run: terraform init

      # Run Terraform plan
      - name: Terraform Plan
        run: terraform plan -input=false

      # Apply changes
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
