name: Testing Workflow Variables

on:
  workflow_dispatch

env:
  cloud: google-cloud   #Here we define the variable name as cloud with the value google-cloud, and this is at the workflow scope, so it can be used throughout the entire workflow.

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello                 #Here we define the variable name as Greeting with the value Hello and this variable scope within job itself
    steps:
      - name: "Say Hello it's Monday"
        run: echo "$Greeting $First_Name is using $cloud!"
        env:
          First_Name: Bikram          #Here we define the variable name as First_Name with the value Bikram This variable scope within steps itself
